spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: {AZURE_TENANT_ID}
        credential:
          client-id: ${AZURE_CLIENT_ID}
          client-secret: ${AZURE_CLIENT_SECRET}
        authorization-clients:
          graph:
            scopes: https://graph.microsoft.com/openid, profile, email
        redirect-uri-template: '{baseUrl}/login/oauth2/code/{registrationId}'

logging:
  level:
    root: debug
server:
  servlet:
    session:
      cookie:
        name: JSESSIONID
        secure: true  # Ensure this is set to true if using HTTPS
        http-only: true
        same-site: None

